<a href="https://colab.research.google.com/github/Javiour2003/Compute_Tasks/blob/main/Task2_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df=pd.read_csv("/content/data.csv")
df.head()

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.0102,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.1990,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.0344,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.6040,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.1800,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys

In [3]:
df

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.01020,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.19900,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.03440,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.60400,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.18000,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,2012,0.00106,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.3330,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.08770,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.1310,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.00857,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.1070,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.00164,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.1330,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.00281,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.1410,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

In [4]:
df.head(10)

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.01020,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.19900,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.03440,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.60400,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.18000,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys
5,5,0.00479,0.804,251333,0.560,0.000000,8,0.1640,-6.682,1,0.1850,85.023,4.0,0.264,1,Sneakin’,Drake
6,6,0.01450,0.739,241400,0.472,0.000007,1,0.2070,-11.204,1,0.1560,80.030,4.0,0.308,1,Childs Play,Drake
7,7,0.02020,0.266,349667,0.348,0.664000,10,0.1600,-11.609,0,0.0371,144.154,4.0,0.393,1,Gyöngyhajú lány,Omega
8,8,0.04810,0.603,202853,0.944,0.000000,11,0.3420,-3.626,0,0.3470,130.035,4.0,0.398,1,I've Seen Footage,Death Grips
9,9,0.00208,0.836,226840,0.603,0.000000,7,0.5710,-7.792,1,0.2370,99.994,4.0,0.386,1,Digital Animal,Honey Claws

In [5]:
df.tail()

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
2012,2012,0.00106,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.333,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.08770,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.131,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.00857,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.107,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.00164,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.133,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.00281,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.141,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

In [6]:
df.tail(10)

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
2007,2007,0.002170,0.639,296276,0.978,0.112000,11,0.0838,-2.376,1,0.0730,144.986,4.0,0.494,0,Let It Go - Scott Melker & Mister Gray Remix,NERVO
2008,2008,0.054100,0.646,160408,0.714,0.000000,0,0.1340,-6.511,1,0.0378,97.957,4.0,0.589,0,"Call On Me - EDWYNN X TIKAL, Spirix Remix",Starley
2009,2009,0.004990,0.595,224000,0.837,0.035900,1,0.1010,-6.011,1,0.0696,149.964,4.0,0.331,0,Aamon,Kuuro
2010,2010,0.002310,0.624,206013,0.971,0.121000,6,0.2550,-0.935,0,0.0643,102.003,4.0,0.442,0,Hey Baby - Steve Aoki Remix,Dimitri Vegas & Like Mike
2011,2011,0.000586,0.528,245053,0.879,0.004890,6,0.0432,-5.891,0,0.1200,128.268,4.0,0.327,0,Brightside - Borgeous Remix,Icona Pop
2012,2012,0.001060,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.3330,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.087700,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.1310,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.008570,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.1070,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.001640,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.1330,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.002810,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.1410,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2017 non-null   int64
 1   acousticness      2017 non-null   float64
 2   danceability      2017 non-null   float64
 3   duration_ms       2017 non-null   int64
 4   energy            2017 non-null   float64
 5   instrumentalness  2017 non-null   float64
 6   key               2017 non-null   int64
 7   liveness          2017 non-null   float64
 8   loudness          2017 non-null   float64
 9   mode              2017 non-null   int64
 10  speechiness       2017 non-null   float64
 11  tempo             2017 non-null   float64
 12  time_signature    2017 non-null   float64
 13  valence           2017 non-null   float64
 14  target            2017 non-null   int64
 15  song_title        2017 non-null   object
 16  artist            2017 non-null   object
dtypes: float64(10), int64(5), object(2)
memory usage: 268.0+ KB

In [8]:
df.sort_values("danceability")["song_title"].head(10)

729                                            Bumpy Road
532                                       Wake Bake Skate
817     Mozart: Requiem in D Minor, K. 626: VIII. Lacr...
1600           Trio Sonata in G Major, Wq. 144: I. Adagio
1598    Piano Quartet in E flat, Op.47: 3. Andante can...
522                                                 Outro
1348                 Be My Valentine (feat. Dickie Allen)
1464                                           Right Here
1313                                      Senseless Order
1306                                                 Ruin
Name: song_title, dtype: object

In [9]:
df.sort_values('danceability')[['song_title', 'artist']].head(10)

,song_title,artist
729,Bumpy Road,Destruction Unit
532,Wake Bake Skate,FIDLAR
817,"Mozart: Requiem in D Minor, K. 626: VIII. Lacr...",Nikolaus Harnoncourt
1600,"Trio Sonata in G Major, Wq. 144: I. Adagio",Carl Philipp Emanuel Bach
1598,"Piano Quartet in E flat, Op.47: 3. Andante can...",Robert Schumann
522,Outro,M83
1348,Be My Valentine (feat. Dickie Allen),Brojob
1464,Right Here,Keys N Krates
1313,Senseless Order,Signs of the Swarm
1306,Ruin,Altered Perceptions

In [10]:
df.sort_values('duration_ms')[['song_title', 'artist', 'duration_ms']].tail(10)

,song_title,artist,duration_ms
1602,"String Quintet in C Major, Op. 29: II. Adagio ...",Ludwig van Beethoven,649415
304,Night on Bald Mountain,Modest Mussorgsky,659560
858,Night on Bald Mountain,Modest Mussorgsky,700027
404,Who Is He And What Is He To You,Creative Source,703107
335,Zombie,Fela Kuti,745653
1565,Gloomy Sunday,Branford Marsalis,763467
1603,Viola Sonata in C Minor: III. Andante con vari...,Felix Mendelssohn,784013
819,Southern Man - Live,"Crosby, Stills, Nash & Young",825027
695,Music Is the Answer - Original Extended 12-Inc...,Celeda,849960
1535,The Nearness of You,Joshua Redman,1004627

In [11]:
df_filt = df[df['duration_ms'] < 400000]
df_filt

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.01020,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.19900,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.03440,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.60400,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.18000,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,2012,0.00106,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.3330,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.08770,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.1310,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.00857,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.1070,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.00164,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.1330,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.00281,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.1410,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

In [12]:
df_filt2 = df_filt.sort_values('energy')[['song_title', 'artist', 'duration_ms','energy']].tail(10)
df_filt2

               song_title                    artist  duration_ms  energy
1296         Black Colors       Victim Of Deception       247533   0.990
1681                Hated                 Beartooth       211430   0.990
1328  Down into the Abyss               Conjonctive       256920   0.991
1680             Paranoia         A Day To Remember       200677   0.992
1332      Beautiful Agony          Within The Ruins       271560   0.992
2015        First Contact                Twin Moons       185600   0.992
1347           Unanswered           Suicide Silence       135653   0.993
1297    A Darkened Gospel      A Wake in Providence       311217   0.994
1322           Pitchblack  Walking Dead On Broadway       221776   0.997
1299        No Absolution         Thy Art Is Murder       201783   0.998

In [13]:
df2 = df_filt2.sort_values('energy',ascending=False)
df2

               song_title                    artist  duration_ms  energy
1299        No Absolution         Thy Art Is Murder       201783   0.998
1322           Pitchblack  Walking Dead On Broadway       221776   0.997
1297    A Darkened Gospel      A Wake in Providence       311217   0.994
1347           Unanswered           Suicide Silence       135653   0.993
1680             Paranoia         A Day To Remember       200677   0.992
1332      Beautiful Agony          Within The Ruins       271560   0.992
2015        First Contact                Twin Moons       185600   0.992
1328  Down into the Abyss               Conjonctive       256920   0.991
1296         Black Colors       Victim Of Deception       247533   0.990
1681                Hated                 Beartooth       211430   0.990

In [14]:
df_filtered = df.sort_values('duration_ms')[['song_title', 'artist', 'duration_ms']].tail(10)
df_filtered

,song_title,artist,duration_ms
1602,"String Quintet in C Major, Op. 29: II. Adagio ...",Ludwig van Beethoven,649415
304,Night on Bald Mountain,Modest Mussorgsky,659560
858,Night on Bald Mountain,Modest Mussorgsky,700027
404,Who Is He And What Is He To You,Creative Source,703107
335,Zombie,Fela Kuti,745653
1565,Gloomy Sunday,Branford Marsalis,763467
1603,Viola Sonata in C Minor: III. Andante con vari...,Felix Mendelssohn,784013
819,Southern Man - Live,"Crosby, Stills, Nash & Young",825027
695,Music Is the Answer - Original Extended 12-Inc...,Celeda,849960
1535,The Nearness of You,Joshua Redman,1004627

In [15]:
df_filtered.to_csv('/content/df_filtered.csv')

In [16]:
df3=pd.read_csv('/content/df_filtered.csv')
df3

,Unnamed: 0,song_title,artist,duration_ms
0,1602,"String Quintet in C Major, Op. 29: II. Adagio ...",Ludwig van Beethoven,649415
1,304,Night on Bald Mountain,Modest Mussorgsky,659560
2,858,Night on Bald Mountain,Modest Mussorgsky,700027
3,404,Who Is He And What Is He To You,Creative Source,703107
4,335,Zombie,Fela Kuti,745653
5,1565,Gloomy Sunday,Branford Marsalis,763467
6,1603,Viola Sonata in C Minor: III. Andante con vari...,Felix Mendelssohn,784013
7,819,Southern Man - Live,"Crosby, Stills, Nash & Young",825027
8,695,Music Is the Answer - Original Extended 12-Inc...,Celeda,849960
9,1535,The Nearness of You,Joshua Redman,1004627

In [18]:
new_df=df[df['energy']>0.4] #filtered the energy values
new_df['song_title'] #dataframe displayed song tiles

0                                   Mask Off
2                               Xanny Family
4                             Parallel Lines
5                                   Sneakin’
6                                Childs Play
                        ...
2012     Like A Bitch - Kill The Noise Remix
2013                                   Candy
2014    Habit - Dack Janiels & Wenzday Remix
2015                           First Contact
2016                      I Wanna Get Better
Name: song_title, Length: 1830, dtype: object

In [19]:
new_df1=df[df['duration_ms']<300000] #filtered the song duration
new_df1.sort_values('tempo',ascending=False)[['song_title','artist','tempo']].tail(10) #sorted the tempo in the descending value

                                       song_title              artist   tempo
176                                    New Slaves          Kanye West  68.456
806               Tupelo (Pt. 1) - Single Version         Albert King  66.711
1564                            You Go To My Head          Art Pepper  65.230
474                        Long Heels Red Bottoms               Trina  64.992
1549                                      Eleanor          Hank Jones  63.938
1542                            Can't Help Loving        Beegie Adair  63.637
1544                         When Sunny Gets Blue         McCoy Tyner  60.483
1406                         Don't You Cry For Me                Cobi  60.391
1532  Journey Into Melody - 2007 Digital Remaster  Stanley Turrentine  59.385
1531    I Was So Young, and You Were So Beautiful        Bill Charlap  47.859

In [32]:
new_df2=df[df['artist']=='Drake']
new_df3=new_df2[new_df2['energy']>0.5][['song_title','energy']]
new_df3

                   song_title  energy
5                    Sneakin’   0.560
37                    Jumpman   0.547
117             Hotline Bling   0.623
154                 Big Rings   0.676
440                 Headlines   0.571
589   Started From the Bottom   0.531
779   0 To 100 / The Catch Up   0.709
1016         Skepta Interlude   0.822
1218          Best I Ever Had   0.861
1223                Take Care   0.527

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2017 non-null   int64
 1   acousticness      2017 non-null   float64
 2   danceability      2017 non-null   float64
 3   duration_ms       2017 non-null   int64
 4   energy            2017 non-null   float64
 5   instrumentalness  2017 non-null   float64
 6   key               2017 non-null   int64
 7   liveness          2017 non-null   float64
 8   loudness          2017 non-null   float64
 9   mode              2017 non-null   int64
 10  speechiness       2017 non-null   float64
 11  tempo             2017 non-null   float64
 12  time_signature    2017 non-null   float64
 13  valence           2017 non-null   float64
 14  target            2017 non-null   int64
 15  song_title        2017 non-null   object
 16  artist            2017 non-null   object
dtypes: float64(10), int64(5), object(2)
memory usage: 268.0+ KB

In [39]:
d=df.sort_values('instrumentalness',ascending=False)[['instrumentalness','song_title','artist']].head(10)
d

,instrumentalness,song_title,artist
1313,0.976,Senseless Order,Signs of the Swarm
271,0.968,So Destroyed (channeling Rage Peace),Prince Rama
1575,0.964,A Hundred Dreams from Now,Ray Bryant
1619,0.958,Raven,John Dahlbäck
725,0.957,Strandbar (disko),Todd Terje
1546,0.956,Almas vaggvisa,Jan Lundgren Trio
1322,0.955,Pitchblack,Walking Dead On Broadway
1349,0.954,Prismatic Abyss,Aversions Crown
1661,0.954,Yebisah,Mark Knight
121,0.952,Chasing Heaven,Bassnectar